### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by khughitt** [apierleoni/BioGraPy#5]
Does BioGraPy support python3?

Just tried installing, but ran into error on import:

```
In [2]: import biograpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b673d121cc25> in <module>()
----> 1 import biograpy

/usr/lib/python3.5/site-packages/biograpy-1.0b0dev_r0-py3.5.egg/biograpy/__init__.py in <module>()
----> 1 from drawer import Panel
      2 from seqrecord import SeqRecordDrawer, SliceSeqRec

ImportError: No module named 'drawer'
```

**Comment by apierleoni** [comment]
Hi, the library does not support python 3. Unfortunately I cannot work on it now, but If you want to contribute I'll be happy to accept the changes.

**Comment by khughitt** [comment]
@apierleoni  no problem - I'll close the issue for now. If I should find myself with extra time in the future though, perhaps I will take a stab at porting it.
